from hitman.hitman import HC

WORLD = [
    [HC.EMPTY,  HC.EMPTY,   HC.EMPTY,   HC.SUIT,    HC.GUARD_S, HC.WALL,        HC.WALL],
    [HC.EMPTY,  HC.WALL,    HC.EMPTY,   HC.EMPTY,   HC.EMPTY,   HC.EMPTY,       HC.EMPTY],
    [HC.TARGET, HC.WALL,    HC.EMPTY,   HC.CIVIL_W, HC.EMPTY,   HC.CIVIL_N,     HC.EMPTY],
    [HC.WALL,   HC.WALL,    HC.EMPTY,   HC.GUARD_E, HC.EMPTY,   HC.CIVIL_W,     HC.CIVIL_E],
    [HC.EMPTY,  HC.EMPTY,   HC.EMPTY,   HC.EMPTY,   HC.EMPTY,   HC.EMPTY,       HC.EMPTY],
    [HC.EMPTY,  HC.CIVIL_W, HC.WALL,    HC.WALL,    HC.EMPTY,   HC.PIANO_WIRE,  HC.EMPTY],
]